using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("Zora Ltd")]
[assembly: AssemblyVersionAttribute("1.0.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.0.1")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.f3758598714fe582d9917e1e823b30add8300fde")]
[assembly: AssemblyTitleAttribute("hr2006")]
[assembly: AssemblyProductAttribute("hr2006")]
[assembly: AssemblyDescriptionAttribute("hr2006 is a product of Zora Ltd - git@svnserver:HR.")]
[assembly: AssemblyTrademarkAttribute("hr2006 - Zora Ltd")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2015 Zora Ltd, - Original author or authors")]

