//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AdminInfo
    {
        public int id { get; set; }
        public string firmName { get; set; }
        public string type { get; set; }
        public string kind { get; set; }
        public string region { get; set; }
        public string town { get; set; }
        public string postalCode { get; set; }
        public string addressData { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string secureNumber { get; set; }
        public Nullable<int> nominalEmployees { get; set; }
        public string bankName { get; set; }
        public string bankAccount { get; set; }
        public string bankcode { get; set; }
        public string directorName { get; set; }
        public string egnDirector { get; set; }
        public string directorLsys { get; set; }
        public string egnDirectorLsys { get; set; }
        public string mainAccountantName { get; set; }
        public string egnMainAccountant { get; set; }
        public string mainConsult { get; set; }
        public string egnMainConsult { get; set; }
        public string trz { get; set; }
        public string egnTrz { get; set; }
        public string additionalInfo { get; set; }
        public string modifiedByUser { get; set; }
        public string bulstat { get; set; }
        public string taxNum { get; set; }
        public string NKIDCode { get; set; }
        public string NKIDLevel { get; set; }
    }
}
