//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AttachedDocs
    {
        public int id { get; set; }
        public int parent { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string typedocument { get; set; }
    }
}
