//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Attestations
    {
        public int id { get; set; }
        public string Year { get; set; }
        public Nullable<int> par { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public string hasWorkplan { get; set; }
        public string hasMiddleMeeting { get; set; }
        public string hasTraining { get; set; }
        public string NextRangUpdate { get; set; }
        public string hasRangUpdate { get; set; }
        public Nullable<System.DateTime> RangUpdateData { get; set; }
        public Nullable<System.DateTime> WorkPlanDate { get; set; }
        public Nullable<System.DateTime> MiddleMeetingDate { get; set; }
        public string ControllingBossName { get; set; }
        public string hasFinalMeeting { get; set; }
        public Nullable<System.DateTime> FinalMeetingDate { get; set; }
        public string NewRang { get; set; }
        public string TrainingData { get; set; }
        public string Others { get; set; }
        public string hasPositionUpdate { get; set; }
        public Nullable<System.DateTime> PositionUpdateDate { get; set; }
        public Nullable<System.DateTime> ObjectionDate { get; set; }
        public string hasObjection { get; set; }
        public string BossName { get; set; }
    }
}
