//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Absence
    {
        public int id { get; set; }
        public Nullable<System.DateTime> orderFromDate { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime toDate { get; set; }
        public int countDays { get; set; }
        public string typeAbsence { get; set; }
        public string numberOrder { get; set; }
        public string reason { get; set; }
        public int parent { get; set; }
        public string modifiedByUser { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> issuedatdate { get; set; }
        public string sicknessduration { get; set; }
        public string Attachment7 { get; set; }
        public string Declaration39 { get; set; }
        public string AdditionalDocs { get; set; }
        public string MKB { get; set; }
        public string reasons { get; set; }
        public string NAPDocs { get; set; }
        public Nullable<int> CalendarDays { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<int> SicknessNumber { get; set; }
    
        public virtual HR_person HR_person { get; set; }
    }
}
