//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EKDA
    {
        public int id { get; set; }
        public string code { get; set; }
        public string level { get; set; }
        public string minSalary { get; set; }
        public string maxSalary { get; set; }
        public string porNum { get; set; }
        public string education { get; set; }
        public string rang { get; set; }
        public string experience { get; set; }
        public string law { get; set; }
    }
}
