//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EducationNomenklature
    {
        public int id { get; set; }
        public string EducationName { get; set; }
        public string EducationCode { get; set; }
        public string EducationArea { get; set; }
        public string NumDays { get; set; }
        public string NumHours { get; set; }
        public string Price { get; set; }
        public string Place { get; set; }
        public string Organisation { get; set; }
    }
}
