//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Educations
    {
        public int id { get; set; }
        public Nullable<int> personid { get; set; }
        public string Area { get; set; }
        public string Theme { get; set; }
        public string Code { get; set; }
        public string EducationDays { get; set; }
        public string EducationHours { get; set; }
        public string Price { get; set; }
        public string CertificateData { get; set; }
        public string EducationPlace { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string EducationOrganisation { get; set; }
    
        public virtual HR_person HR_person { get; set; }
    }
}
