//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Fired
    {
        public Nullable<int> parent { get; set; }
        public int id { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string CompensationWork { get; set; }
        public string CompensationTime { get; set; }
        public string NumberSalary { get; set; }
        public string Compensation { get; set; }
        public Nullable<int> CountDays { get; set; }
        public string level1 { get; set; }
        public string level2 { get; set; }
        public string level3 { get; set; }
        public string level4 { get; set; }
        public string position { get; set; }
        public string baseSalary { get; set; }
        public string modifiedbyuser { get; set; }
        public string fireorder { get; set; }
        public Nullable<System.DateTime> FireOrderDate { get; set; }
    
        public virtual HR_person HR_person { get; set; }
    }
}
