//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_FirmPersonal3
    {
        public int id { get; set; }
        public string nameOfPosition { get; set; }
        public string StaffCount { get; set; }
        public string KVS { get; set; }
        public Nullable<int> NumMonths { get; set; }
        public string SecurityLevel { get; set; }
        public string EKDACode { get; set; }
        public string EKDALevel { get; set; }
        public string VOS { get; set; }
        public string PMS { get; set; }
        public string AdditionNumber { get; set; }
        public string PorNum { get; set; }
        public string Law { get; set; }
        public string NKPCode { get; set; }
        public string nKPlevel { get; set; }
        public string education { get; set; }
        public string rang { get; set; }
        public string Experience { get; set; }
        public string OtherRequirements { get; set; }
        public string MinSalary { get; set; }
        public string MaxSalary { get; set; }
        public Nullable<double> free { get; set; }
        public Nullable<double> busy { get; set; }
        public Nullable<int> par { get; set; }
        public string Notes { get; set; }
        public string TypePosition { get; set; }
        public Nullable<int> StaffOrder { get; set; }
        public string BasicDuties { get; set; }
        public string BasicResponsibilities { get; set; }
        public string Competence { get; set; }
        public string Connections { get; set; }
        public string Requirements { get; set; }
        public string NKPClass { get; set; }
        public string StartSalary { get; set; }
        public string BaseSalary { get; set; }
        public string SalaryAddon { get; set; }
        public string ScienceAddon { get; set; }
        public string OtherAddon { get; set; }
        public string positioneng { get; set; }
        public Nullable<int> globalpositionid { get; set; }
        public string ekdaPayLEvel { get; set; }
    }
}
