//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_FirmStructure
    {
        public string direction { get; set; }
        public string control { get; set; }
        public string team { get; set; }
        public string administration { get; set; }
        public int id { get; set; }
    }
}
