//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_GlobalPositions
    {
        public int id { get; set; }
        public string PositionName { get; set; }
        public string EKDALevel { get; set; }
        public string EKDACode { get; set; }
        public string PorNum { get; set; }
        public string PMS { get; set; }
        public string VOS { get; set; }
        public string NKPCode { get; set; }
        public string NKPLevel { get; set; }
        public string Rang { get; set; }
        public string Experience { get; set; }
        public string Education { get; set; }
        public string Law { get; set; }
        public string Minsalary { get; set; }
        public string MaxSalary { get; set; }
        public string TypePosition { get; set; }
        public string BasicDuties { get; set; }
        public string BasicResponsibilities { get; set; }
        public string Connections { get; set; }
        public string Competence { get; set; }
        public string Requirements { get; set; }
        public string NKPClass { get; set; }
        public string engposition { get; set; }
    }
}
