//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Messages
    {
        public int id_message { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_user { get; set; }
        public int id_messageInstance { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsMailSent { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual HR_MessageInstances HR_MessageInstances { get; set; }
    }
}
