//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_MessageTypes
    {
        public HR_MessageTypes()
        {
            this.HR_MessageInstances = new HashSet<HR_MessageInstances>();
        }
    
        public int id_messageType { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<HR_MessageInstances> HR_MessageInstances { get; set; }
    }
}
