//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_NotesTable
    {
        public int id { get; set; }
        public int par { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string type { get; set; }
        public string typedocument { get; set; }
        public string modifiedbyuser { get; set; }
    
        public virtual HR_person HR_person { get; set; }
    }
}
