//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Options
    {
        public int id { get; set; }
        public Nullable<double> classcoef { get; set; }
        public Nullable<int> incrementclass { get; set; }
        public Nullable<int> incrementholiday { get; set; }
        public Nullable<int> holidaycoef { get; set; }
        public Nullable<int> vacancystash { get; set; }
        public Nullable<int> firedsignal { get; set; }
        public string personorder { get; set; }
    }
}
