//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Penalty
    {
        public Nullable<System.DateTime> fromDate { get; set; }
        public string numberOrder { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int id { get; set; }
        public Nullable<int> parent { get; set; }
        public string modifiedByUser { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public string typePenalty { get; set; }
        public string isBonus { get; set; }
    
        public virtual HR_person HR_person { get; set; }
    }
}
