//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PlannedHolidays
    {
        public int id_plannedHoliday { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> par { get; set; }
        public string Jan { get; set; }
        public Nullable<int> JanDays { get; set; }
        public string Feb { get; set; }
        public Nullable<int> FebDays { get; set; }
        public string Mar { get; set; }
        public Nullable<int> MarDays { get; set; }
        public string Apr { get; set; }
        public Nullable<int> AprDays { get; set; }
        public string May { get; set; }
        public Nullable<int> MayDays { get; set; }
        public string Jun { get; set; }
        public Nullable<int> JunDays { get; set; }
        public string Jul { get; set; }
        public Nullable<int> JulDays { get; set; }
        public string Aug { get; set; }
        public Nullable<int> AugDays { get; set; }
        public string Sep { get; set; }
        public Nullable<int> SepDays { get; set; }
        public string Oct { get; set; }
        public Nullable<int> OctDays { get; set; }
        public string Nov { get; set; }
        public Nullable<int> NovDays { get; set; }
        public string Dec { get; set; }
        public Nullable<int> DecDays { get; set; }
    
        public virtual HR_person HR_person { get; set; }
    }
}
