//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PersonAssignment
    {
        public string contractType { get; set; }
        public string nkpCode { get; set; }
        public string nkpLevel { get; set; }
        public string EKDACode { get; set; }
        public string EKDALevel { get; set; }
        public string classPercent { get; set; }
        public string salaryAddon { get; set; }
        public string baseSalary { get; set; }
        public string numberKids { get; set; }
        public Nullable<System.DateTime> contractExpiry { get; set; }
        public string contractNumber { get; set; }
        public string assignReason { get; set; }
        public Nullable<System.DateTime> assignedAt { get; set; }
        public string worktime { get; set; }
        public string contract { get; set; }
        public string position { get; set; }
        public string level3 { get; set; }
        public string level2 { get; set; }
        public string level1 { get; set; }
        public Nullable<int> IsAdditionalAssignment { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<int> isActive { get; set; }
        public int id { get; set; }
        public string modifiedByUser { get; set; }
        public Nullable<int> years { get; set; }
        public Nullable<int> months { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> positionID { get; set; }
        public string parentContractId { get; set; }
        public string law { get; set; }
        public string level4 { get; set; }
        public string YearlyAddon { get; set; }
        public Nullable<int> PrevAssignmentID { get; set; }
        public string MonthlyAddon { get; set; }
        public Nullable<System.DateTime> ParentContractDate { get; set; }
        public string Rang { get; set; }
        public string NumHoliday { get; set; }
        public Nullable<System.DateTime> TestContractDate { get; set; }
        public Nullable<int> AdditionalHoliday { get; set; }
        public Nullable<int> ExperienceCorrection { get; set; }
        public Nullable<int> exported { get; set; }
        public string pcontractreasoncode { get; set; }
        public Nullable<int> substitute { get; set; }
        public Nullable<double> staff { get; set; }
        public string level1eng { get; set; }
        public string level2eng { get; set; }
        public string level3eng { get; set; }
        public string level4eng { get; set; }
        public string positioneng { get; set; }
        public string tutorname { get; set; }
        public string tutorabsencereason { get; set; }
        public Nullable<int> ekdaPayDegree { get; set; }
    
        public virtual HR_person HR_person { get; set; }
    }
}
