//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_YearWorkdays
    {
        public int id_yearWorkdays { get; set; }
        public bool IsHoliday { get; set; }
        public int Year { get; set; }
        public System.DateTime Date { get; set; }
    }
}
