//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HR_Absence> HR_Absence { get; set; }
        public DbSet<HR_AdminInfo> HR_AdminInfo { get; set; }
        public DbSet<HR_AttachedDocs> HR_AttachedDocs { get; set; }
        public DbSet<HR_Attestations> HR_Attestations { get; set; }
        public DbSet<HR_Education> HR_Education { get; set; }
        public DbSet<HR_EducationNomenklature> HR_EducationNomenklature { get; set; }
        public DbSet<HR_Educations> HR_Educations { get; set; }
        public DbSet<HR_EKDA> HR_EKDA { get; set; }
        public DbSet<HR_Fired> HR_Fired { get; set; }
        public DbSet<HR_FirmPersonal3> HR_FirmPersonal3 { get; set; }
        public DbSet<HR_FirmStructure> HR_FirmStructure { get; set; }
        public DbSet<HR_GlobalPositions> HR_GlobalPositions { get; set; }
        public DbSet<HR_JoinNomenklature> HR_JoinNomenklature { get; set; }
        public DbSet<HR_LanguageLevel> HR_LanguageLevel { get; set; }
        public DbSet<HR_MessageInstances> HR_MessageInstances { get; set; }
        public DbSet<HR_Messages> HR_Messages { get; set; }
        public DbSet<HR_MessageTypes> HR_MessageTypes { get; set; }
        public DbSet<HR_Newtree2> HR_Newtree2 { get; set; }
        public DbSet<HR_NKID> HR_NKID { get; set; }
        public DbSet<HR_nkp> HR_nkp { get; set; }
        public DbSet<HR_Notes> HR_Notes { get; set; }
        public DbSet<HR_NotesTable> HR_NotesTable { get; set; }
        public DbSet<HR_Options> HR_Options { get; set; }
        public DbSet<HR_Penalty> HR_Penalty { get; set; }
        public DbSet<HR_person> HR_person { get; set; }
        public DbSet<HR_PersonAssignment> HR_PersonAssignment { get; set; }
        public DbSet<HR_Pictures> HR_Pictures { get; set; }
        public DbSet<HR_PlannedHolidays> HR_PlannedHolidays { get; set; }
        public DbSet<HR_ReasonAssignment> HR_ReasonAssignment { get; set; }
        public DbSet<HR_StructureHistory> HR_StructureHistory { get; set; }
        public DbSet<HR_Users> HR_Users { get; set; }
        public DbSet<HR_worktime> HR_worktime { get; set; }
        public DbSet<HR_Year> HR_Year { get; set; }
        public DbSet<HR_Year_Holiday> HR_Year_Holiday { get; set; }
        public DbSet<HR_YearWorkdays> HR_YearWorkdays { get; set; }
    }
}
